name: VisFly-3.12
channels:
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - cmake>=3.27
  - cuda-version=12.9
  - pip:
      - attrs
      - gymnasium==1.2.3
      - imageio
      - imageio-ffmpeg
      - matplotlib
      - networkx
      - numpy
      - numpy-quaternion
      - opencv-python
      - pandas
      - pillow
      - pyyaml
      - scikit-learn
      - scipy
      - stable-baselines3==2.8.0
      - tensorboard
      - --extra-index-url https://download.pytorch.org/whl/cu129
      - torch==2.11.0+cu129
      - torchaudio==2.11.0+cu129
      - torchvision==0.26.0+cu129
      - tqdm
